### ISSUE TITLE
[BUG] 登陆漏洞与隐患，请大大协助修复，避免影响扩大

### ISSUE THREAD

**Issue by macaty** [dromara/hertzbeat#1144]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

HertzBeat监控系统任意登录漏洞，麻烦协助
1、伪造登陆+token
输入admin账号，密码随意输入，点击登录，替换返回数据包为：
{"data":{"token":"eyJhbGciOiJIUzUxMiIsInppcCI6IkRFRiJ9.eJw9jEsKwzAMRO-idQS2Cf7kKqULJ1LB_TjFskOh5O5xoHQ5b2beF-41wQR6iZq8IhwpOBxDdDg7cmiC99obUvq2wADS5j6O9Eq5pyTSk7TCmUWwrg_OKFw2LmcbK0zaBuW8tcYMwJ_3DwRlTlDWJ3fD5S9s_QzX_QB7_itQ.4IZLf22QI6aXwWfByp8MHu33BUxKOYO4HR36h9l5ATlAqQoVj47bMfNDnXlKnmFADBUXmYb0AzoBw5301f-xhw","refreshToken":"eyJhbGciOiJIUzUxMiIsInppcCI6IkRFRiJ9.eJwliksOwiAQQO8y65IA5X8bikNEI5oZ2pgY7y6Ny_f5wG00SFBqxjX4IHy2VRi7RhEdViGlMsVEq8vmYQHetznny6P1SY15Eu-EHZnFeN6xC0Y6kM6aByTlovTBOa0XwPfrL6JU4RSElZCvkAbt-P0B5Y0org.ok308qgxAD--_x6jT-uGIVPJtptdZGN72n1yh_k_QWpPFjIeHNnXsQ9UtZip6SQOdx1c4NXJfsDnyrwfJhEOcw"},"msg":null,"code":0}
成功接管系统后台
![image](https://github.com/dromara/hertzbeat/assets/16797633/a41d49f9-8710-4076-94a2-f1fd78388742)
![image](https://github.com/dromara/hertzbeat/assets/16797633/f794e445-9035-4649-8459-c8a6adebcfdf)
2、可以随意查看数据实例等明文用户名和密码，例如Redis
![image](https://github.com/dromara/hertzbeat/assets/16797633/a9e59316-d9de-4778-9385-b18a03f0f723)

3、建议：
-->帐号登陆需要强验证，避免伪造token越权登陆
-->监控设置需要脱敏，避免复制帐号、密码

**Comment by tomsun28** [comment]
hi 感谢反馈👍
1. 伪造后台token成功是因为密钥相同导致的，可以在 application.yml 修改 sureness.jwt.secret 为自定义的密钥 
```yaml
sureness:
  auths:
    - digest
    - basic
    - jwt
  jwt:
    secret: 'CyaFv0bwq2Eik0jdrKUtsA6bx3sDJeFV643R
             LnfKefTjsIfJLBa2YkhEqEGtcHDTNe4CU6+9
             8tVt4bisXQ13rbN0oxhUZR73M6EByXIO+SV5
             dKhaX0csgOCTlCxq20yhmUea6H6JIpSE2Rwp'
```

这块确实有问题，我们应该在对用户没有修改密钥的情况下，日志ERROR提醒修改为自定义的密钥

2.当用户进入系统后，他是并不能查看到真实的监控密码参数的，因为我们对每个监控密码参数都做了加密保护，页面显示的是一个加密后的密码串

我看页面应该版本比较老了 建议升级最新版本

**Comment by hertzbeat** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
hi thanks for the feedback 👍
1. The successful forgery of the background token is caused by the same key, you can modify the sureness.jwt.secret in application.yml to a custom key
```yaml
sureness:
  auths:
    -digest
    - basic
    - jwt
  jwt:
    secret: 'CyaFv0bwq2Eik0jdrKUtsA6bx3sDJeFV643R
             LnfKefTjsIfJLBa2YkhEqEGtcHDTNe4CU6+9
             8tVt4bisXQ13rbN0oxhUZR73M6EByXIO+SV5
             dKhaX0csgOCTlCxq20yhmUea6H6JIpSE2Rwp'
```

There is indeed a problem with this piece. We should change the log ERROR to a custom key without modifying the key for the user.

2. When the user enters the system, he cannot view the real monitoring password parameters, because we have encrypted and protected each monitoring password parameter, and the page displays an encrypted password string

I think the version of the page should be relatively old, it is recommended to upgrade to the latest version
