### ISSUE TITLE
[Question] deploy on k8s，collector do not connect manager

### ISSUE THREAD

**Issue by lgfei** [dromara/hertzbeat#1183]
### Question

collector connect cluster server error: Connection refused: /xxx:1158. try after 10s.

**Comment by tomsun28** [comment]
hi please  confirm the hertzbeat server port 1158 is listening and the collector network can access the hertzbeat server ip 
```
-e MANAGER_IP=127.0.0.1 
-e MANAGER_PORT=1158
```

**Comment by lgfei** [comment]
I resolved. 
Cause by application.yml missing config, as follows
```yml
    scheduler:
      server:
        enabled: true
        port: 1158
```
