### ISSUE TITLE
[BUG] <Ping timeout is automatically reset to 65535>

### ISSUE THREAD

**Issue by Kylin-Guo** [dromara/hertzbeat#1210]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

在app-ping.yml文件中，数字的区间范围是0~100000，但在Web页面中设置监控时若输入的数值大于65535则会自动重置为65535，不能往上增加

![image](https://github.com/dromara/hertzbeat/assets/131239856/1304cf93-3ecd-408a-85f3-b83fc0b73e33)

### Environment

```markdown
HertzBeat version(s):1.4.0
```

**Comment by tomsun28** [comment]
thanks, got it.

**Comment by hertzbeat** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
thanks, got it.

**Comment by qyaaaa** [comment]
```
    name:
      zh-CN: Ping超时时间(ms)
      en-US: Ping Timeout(ms)
    # type-param field type(most mapping the html input type)
    # type-字段类型,样式(大部分映射input标签type属性)
    type: number
    # when type is number, range is required
    # 当type为number时,用range表示范围
    range: '[0,100000]'
    # required-true or false
    # 是否是必输项 true-必填 false-可选
    required: true
    # default value 6000
    # 默认值 6000
    defaultValue: 6000
```
有许多type为number但range不为'[0,65535]'复用了同一个组件，前端限制为 [nzMin]="-1000" [nzMax]="65535" ，有什么好的想法解决这个问题吗？或许我可以帮忙修复它。
