### ISSUE TITLE
[Task] Monitoring Template Yml Metrics I18n | 监控模版指标国际化任务认领 

### ISSUE THREAD

**Issue by tomsun28** [dromara/hertzbeat#1212]
### Description

**Monitoring Template Yml Metrics I18n Task**  
> 监控模版指标国际化任务认领  

Hi guys, in the past, the `Metrics Name` of `HertzBeat` monitoring details could only display the English field, and could not support the configuration to display international name aliases such as English and Chinese. We are very glad that this version supports it. We have configured the internationalized name of the metrics into the monitoring template YML of each monitoring type. Because there are too many monitoring templates and the translation of the metrics name of each monitoring type needs to be considered, so I ask for your help here. Interested partners are welcome to cooperate and contribute to the internationalization of the monitoring template metrics translation. Thanks!

> 小伙伴们大家好，之前`HertzBeat`的监控详情的`指标名称`只能展示英文指标field字段，无法支持配置展示英文中文等国际化名称别名。很高兴这个版本我们对其支持了，指标的国际化名称我们将其配置到了各个监控类型的监控模版YML中。因为监控模版实在太多且每个监控类型的指标名称翻译都需要考量，所以在这里请求大家的帮助，欢迎感兴趣的小伙伴协作贡献大家一起把监控模版指标翻译国际化做好。谢谢，爱心💗！

Demo before:

<img width="1349" alt="image" src="https://github.com/dromara/hertzbeat/assets/24788200/46197c44-f184-43da-8ce6-6b17a2f0c16f">

After Metrics I18n:

<img width="1370" alt="image" src="https://github.com/dromara/hertzbeat/assets/24788200/8b89c63f-7e74-4b02-875d-d34eef28b2d4">

### Task List

Just comment on the corresponding task under this issue, and one PR corresponds to one monitoring template YML. as follows:   
> 领取方式，在本 issues 下评论对应任务即可，一个PR对应一个监控模版YML。如下:

- [x] Metrics I18n https://github.com/dromara/hertzbeat/blob/master/manager/src/main/resources/define/app-zookeeper.yml

```
- [x] Metrics I18n https://github.com/dromara/hertzbeat/blob/master/manager/src/main/resources/define/app-zookeeper.yml

```
Add i18n translation content under the metrics group and fields, for example: `i18n.zh-CN: CPU 信息 i18n.en-US: CPU Info`, English and Chinese are required, please pay attention to format alignment.

在指标组和指标下面添加i18n翻译内容, 例如：`i18n.zh-CN: CPU 信息 i18n.en-US: CPU Info`，需支持英文和中文，请注意格式对齐。  

Example: 
```
  - name: cpu
    i18n:
      zh-CN: CPU 信息
      en-US: CPU Info
    priority: 1
    fields:
      - field: info
        type: 1
        i18n:
          zh-CN: 型号
          en-US: Info
      - field: cores
        type: 0
        i18n:
          zh-CN: 核数
          en-US: Cores
      - field: interrupt
        type: 0
        i18n:
          zh-CN: 中断数
          en-US: Interrupt
      - field: load
        type: 1
        i18n:
          zh-CN: 负载
          en-US: Load
      - field: context_switch
        type: 0
        i18n:
          zh-CN: 上下文切换
          en-US: Context Switch
      - field: usage
        type: 0
        unit: '%'
        i18n:
          zh-CN: 使用率
          en-US: Usage
```
