### ISSUE TITLE
我不知道为什么，始终看不到监控数据。

### ISSUE THREAD

**Issue by aitting** [dromara/hertzbeat#1679]
### Question

我不知道为什么，始终看不到监控数据。

这是模板定义
```yml
category: service
app: api 2
name:
  zh-CN: 自定义HTTP API
  en-US: HTTP API
help:
  zh-CN: Hertzbeat 将调用 HTTP API 接口，查看接口是否可用，并以 ms 为指标单位对其响应时间等指标进行监测。您可以先点击“新增 HTTP API”按钮并进行配置，或在“更多操作”中导入已有配置。
  en-US: The platform will invoke an HTTP API endpoint to verify its accessibility and monitor various metrics, including response time, measured in milliseconds (ms). <br>To set up this functionality, you could click the "Add HTTP API" button and proceed with the configuration or import an existing setup through the "More Actions" menu.
  zh-TW: Hertzbeat將調用HTTP API介面，查看介面是否可用，並以ms為名額組織對其回應時間等名額進行監測。 您可以先點擊“新增HTTP API”按鈕並進行配寘，或在“更多操作”中導入已有配寘。
helpLink:
  zh-CN: https://hertzbeat.com/zh-cn/docs/help/api
  en-US: https://hertzbeat.com/docs/help/api
params:
- field: host
  name:
    zh-CN: 目标Host
    en-US: Target Host
  type: host
  required: true
  range: 
  defaultValue: 
  placeholder: 
  hide: false
  limit: 0
  options: []
  keyAlias: 
  valueAlias: 
- field: port
  name:
    zh-CN: 端口
    en-US: Port
  type: number
  required: true
  range: '[0,65535]'
  defaultValue: 80
  placeholder: 
  hide: false
  limit: 0
  options: []
  keyAlias: 
  valueAlias: 
- field: method
  name:
    zh-CN: 请求方式
    en-US: Method
  type: radio
  required: true
  range: 
  defaultValue: 
  placeholder: 
  hide: false
  limit: 0
  options:
  - label: GET
    value: GET
  - label: POST
    value: POST
  - label: PUT
    value: PUT
  - label: DELETE
    value: DELETE
  keyAlias: 
  valueAlias: 
- field: uri
  name:
    zh-CN: 相对路径
    en-US: URI
  type: text
  required: false
  range: 
  defaultValue: 
  placeholder: Website uri path(no ip port) EG:/v2/book/bar
  hide: false
  limit: 200
  options: []
  keyAlias: 
  valueAlias: 
- field: ssl
  name:
    zh-CN: 启用HTTPS
    en-US: HTTPS
  type: boolean
  required: true
  range: 
  defaultValue: 
  placeholder: 
  hide: false
  limit: 0
  options: []
  keyAlias: 
  valueAlias: 
- field: timeout
  name:
    zh-CN: 超时时间(ms)
    en-US: Timeout(ms)
  type: number
  required: false
  range: 
  defaultValue: 
  placeholder: 
  hide: true
  limit: 0
  options: []
  keyAlias: 
  valueAlias: 
- field: headers
  name:
    zh-CN: 请求Headers
    en-US: Headers
  type: key-value
  required: false
  range: 
  defaultValue: 
  placeholder: 
  hide: false
  limit: 0
  options: []
  keyAlias: Header Name
  valueAlias: Header Value
- field: params
  name:
    zh-CN: 查询Params
    en-US: Params
  type: key-value
  required: false
  range: 
  defaultValue: 
  placeholder: 
  hide: false
  limit: 0
  options: []
  keyAlias: Param Key
  valueAlias: Param Value
- field: contentType
  name:
    zh-CN: Content-Type
    en-US: Content-Type
  type: text
  required: false
  range: 
  defaultValue: 
  placeholder: Request Body Type
  hide: true
  limit: 0
  options: []
  keyAlias: 
  valueAlias: 
- field: payload
  name:
    zh-CN: 请求BODY
    en-US: BODY
  type: textarea
  required: false
  range: 
  defaultValue: 
  placeholder: Available When POST PUT
  hide: true
  limit: 0
  options: []
  keyAlias: 
  valueAlias: 



- field: successCode
  name:
    zh-CN: 校验成功状态码
    en-US: Verify Success Code
  type: array
  required: false
  range: 
  defaultValue: 200, 201
  placeholder: Input Http Status Code
  hide: true
  limit: 0
  options: []
  keyAlias: 
  valueAlias: 
metrics:
- name: summary
  priority: 1
  fields:
  - field: displayName
    type: 1
    label: false
    unit: 
  - field: name
    type: 1
    label: false
    unit: 
  aliasFields: 
  calculates: 
  protocol: http
  http:
    host: ^_^host^_^
    port: ^_^port^_^
    url: ^_^uri^_^
    timeout: ^_^timeout^_^
    method: ^_^method^_^
    ssl: ^_^ssl^_^
    payload: ^_^payload^_^
    headers:
      content-type: ^_^contentType^_^
      ^_^headers^_^: ^_^headers^_^
    params:
      ^_^params^_^: ^_^params^_^
    successCodes:
    - ^_^successCode^_^
    parseType: jsonPath
    keyword: '$.groups[*]'
```
这里接口返回的json
```json
{
"groups":[
 {
    "name": "FileManagement",
    "displayName": "文件上传权限",
    "multiTenancySide": 3,
    "permissions": [
      {
        "name": "FileManagement.DirectoryDescriptor",
        "displayName": "目录",
        "isEnabled": true,
        "multiTenancySide": 3,
        "feature": null,
        "children": [
          {
            "name": "FileManagement.DirectoryDescriptor.Create",
            "displayName": "创建",
            "isEnabled": true,
            "multiTenancySide": 3,
            "feature": null,
            "children": []
          },
          {
            "name": "FileManagement.DirectoryDescriptor.Update",
            "displayName": "更新",
            "isEnabled": true,
            "multiTenancySide": 3,
            "feature": null,
            "children": []
          },
          {
            "name": "FileManagement.DirectoryDescriptor.Delete",
            "displayName": "删除",
            "isEnabled": true,
            "multiTenancySide": 3,
            "feature": null,
            "children": []
          }
        ]
      },
      {
        "name": "FileManagement.FileDescriptor",
        "displayName": "文件",
        "isEnabled": true,
        "multiTenancySide": 3,
        "feature": null,
        "children": [
          {
            "name": "FileManagement.FileDescriptor.Create",
            "displayName": "创建",
            "isEnabled": true,
            "multiTenancySide": 3,
            "feature": null,
            "children": []
          },
          {
            "name": "FileManagement.FileDescriptor.Update",
            "displayName": "更新",
            "isEnabled": true,
            "multiTenancySide": 3,
            "feature": null,
            "children": []
          },
          {
            "name": "FileManagement.FileDescriptor.Delete",
            "displayName": "删除",
            "isEnabled": true,
            "multiTenancySide": 3,
            "feature": null,
            "children": []
          }
        ]
      }
    ],
    "features": [],
    "isEnabled": true
  }
]
}
```
这个是日志
![image](https://github.com/dromara/hertzbeat/assets/69186167/47c7c389-7fd3-42db-bcbf-6919c9b91692)
