### ISSUE TITLE
[Question] <告警通知策略增加阈值设置>

### ISSUE THREAD

**Issue by WillPangZi** [dromara/hertzbeat#328]
### Question

被监控服务器在国外，经常会出现网络连接导致的告警，实际下次检测就立即恢复了，这种告警意义不大。
希望能够在通知策略处增加阈值，比如：
 连续3次出现告警那么进行通知

**Comment by tomsun28** [comment]
收到 🫡 我们考虑下

**Comment by tomsun28** [comment]
hi @WillPangZi 给忘了这个我们已经支持 设置application.yml配置文件的
```
alerter:
  # custom console url
  console-url: https://console.tancloud.cn
  # base of alert eval interval time, unit:ms. The next time is 2 times the previous time.
  alert-eval-interval-base: 600000
  # max of alert eval interval time, unit:ms
  max-alert-eval-interval: 86400000
  # system alert(available alert, reachable alert...) trigger times
  system-alert-trigger-times: 1
```
中的 ` system-alert-trigger-times` 参数为3次，可用性告警则会触发三次才会发告警
