### ISSUE TITLE
[BUG] springboot2.0 monitor health  "status": "DOWN"  No Metrics Data

### ISSUE THREAD

**Issue by jvhuaxia** [dromara/hertzbeat#978]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

springboot2.0 monitor health { "status": "DOWN" }  collected donotwork and show No Metrics Data
but  "status": "UP" collected work

### Environment

```markdown
HertzBeat version(s):
1.2.3
```

**Comment by jvhuaxia** [comment]
![image](https://github.com/dromara/hertzbeat/assets/29006793/46f7843f-a27e-4575-a2fc-60bf3c06680c)
![image](https://github.com/dromara/hertzbeat/assets/29006793/c9fba37f-c738-4c0a-867c-b405f592c063)
i think is the http code problem
can i edit app-springboot2.yml config file ignore this 503 code to collected DOWN data?

**Comment by tomsun28** [comment]
> can i edit app-springboot2.yml config file ignore this 503 code to collected DOWN data?     

@jvhuaxia current not support. weclome to update collecting metrics code to implement this.

**Comment by tomsun28** [comment]
Design Http Collect YML Format.
Add successCode field, the successCode means what http response status code we consider it collect success. 

```
    http:
      host: ^_^host^_^
      port: ^_^port^_^
      url: ^_^base_path^_^/health
      method: GET
      ssl: ^_^ssl^_^
      successCode: 200,503
      parseType: default
```
